spring:
  application:
    name: auth-service

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  datasource:
    username: root
    password: root

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080

  profiles:
    active: dev

server:
  port: 8080
  servlet:
#    context-path: /api/v1
    session:
      cookie:
        same-site: lax
        http-only: true
        secure: false

app:
  kafka:
    topics:
      user-event: user-events

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
    org.springframework.web: TRACE
    org.flywaydb: DEBUG

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:file:./auth-service/database
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/gamevault
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect