spring:
  application:
    name: gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080

  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - http://localhost:3000
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - "*"
                allowCredentials: true

          routes:
            - id: auth-oauth
              uri: http://localhost:8080
              predicates:
                - Path=/oauth2/**,/.well-known/**,/userinfo,/connect/**

            - id: auth-authenticate
              uri: http://localhost:8080
              predicates:
                - Path=/api/authenticate

            - id: auth-api
              uri: http://localhost:8080
              predicates:
                - Path=/api/auth/**

            - id: igdb-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/igdb/**

            - id: user-game-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/v1/users/games/**

            - id: achievement-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/v1/users/achievements/**

server:
  port: 8088

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway